openapi: "3.0.0"
info:
  version: 1.0.0
  title: File Share Service
  license:
    name: MIT
servers:
  - url: http://localhost:8000/v1
paths:
  /files:
    get:
      summary: List all files
      operationId: listFiles
      tags:
        - files
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of files
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Files"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a file object metadata
      operationId: createFile
      tags:
        - files
      responses:
        "200":
          description: Successful file object metadata creation request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
              examples:
                v1:
                  value:
                    {
                      "Status": "CREATING",
                      "StartTime": "2022-06-19T10:52:00Z",
                      "FileId": "aafb42c4-a344-45af-9701-c745d3a2b3c5",
                      "OwnerId": "7bba4642-bf32-48b8-a41b-28a3750c1c3b",
                      "Tags": [],
                    }
        "201":
          description: Null response
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /files/{fileId}:
    get:
      summary: Retrieve specific file object metadata properties
      operationId: getFileById
      tags:
        - files
      parameters:
        - name: fileId
          in: path
          required: true
          description: The id of the file object to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
              examples:
                v1:
                  value:
                    {
                      "Status": "AVAILABLE",
                      "CreationTime": "2022-06-19T10:52:00Z",
                      "FileId": "aafb42c4-a344-45af-9701-c745d3a2b3c5",
                      "OwnerId": "7bba4642-bf32-48b8-a41b-28a3750c1c3b",
                      "Tags": [],
                    }
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete a file object content and metadata properties
      operationId: deleteFileById
      tags:
        - files
      parameters:
        - name: fileId
          in: path
          required: true
          description: The id of the file object to delete
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
              examples:
                v1:
                  value:
                    {
                      "Status": "DELETING",
                      "DeletionTime": "2022-06-19T10:52:00Z",
                      "FileId": "aafb42c4-a344-45af-9701-c745d3a2b3c5",
                      "OwnerId": "7bba4642-bf32-48b8-a41b-28a3750c1c3b",
                      "Tags": [],
                    }
  /files/{fileId}/upload:
    post:
      summary: Upload a file
      operationId: uploadFile
      tags:
        - files
      parameters:
        - name: fileId
          in: path
          required: true
          description: The id of the file to upload
          schema:
            type: string
      responses:
        "200":
          description: Successful file upload request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
              examples:
                v1:
                  value:
                    {
                      "Status": "SYNCING",
                      "UploadTime": "2022-06-19T10:52:00Z",
                      "FileId": "aafb42c4-a344-45af-9701-c745d3a2b3c5",
                      "OwnerId": "7bba4642-bf32-48b8-a41b-28a3750c1c3b",
                      "Tags": [],
                    }
        "201":
          description: Null response
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /files/{fileId}/download:
    get:
      summary: Download a file
      operationId: downloadFileById
      tags:
        - files
      parameters:
        - name: fileId
          in: path
          required: true
          description: The id of the file to download
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
components:
  schemas:
    File:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
        creation_time:
          type: string
          format: date-time
        upload_time:
          type: string
          format: date-time
        deletion_time:
          type: string
          format: date-time
        owner_id:
          type: string
          format: uuid
        tags:
          type: array
          items:
            type: string
    Files:
      type: array
      items:
        $ref: "#/components/schemas/File"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
